import { Album } from './types';

export const VERIFIED_VISUAL_ANALYSIS_VERSION = 'visual-grid-v3';

function isUnitInterval(value: unknown): value is number {
  return typeof value === 'number' && Number.isFinite(value) && value >= 0 && value <= 1;
}

function hasValidPalette(album: Album): boolean {
  const palette = album.dominantPalette;
  if (!Array.isArray(palette) || palette.length === 0) return false;
  const totalWeight = palette.reduce((sum, color) => (
    sum + (Number.isFinite(color.weight) && color.weight > 0 ? color.weight : 0)
  ), 0);
  return totalWeight > 0 && palette.every((color) => (
    /^#[0-9a-f]{6}$/i.test(color.hex) &&
    Array.isArray(color.lab) &&
    color.lab.length === 3 &&
    color.lab.every(Number.isFinite)
  ));
}

function hasValidColorProfile(album: Album): boolean {
  const profile = album.visualFeatures?.colorProfile;
  return Boolean(
    profile &&
    isUnitInterval(profile.neutralCoverage) &&
    isUnitInterval(profile.chromaticCoverage) &&
    Number.isFinite(profile.dominantHue) &&
    profile.dominantHue >= 0 &&
    profile.dominantHue < 360 &&
    isUnitInterval(profile.hueConcentration) &&
    isUnitInterval(profile.meanLightness) &&
    isUnitInterval(profile.lightnessSpread) &&
    profile.neutralCoverage + profile.chromaticCoverage >= 0.95 &&
    profile.neutralCoverage + profile.chromaticCoverage <= 1.05
  );
}

function hasNormalizedDescriptor(embedding: number[] | undefined): boolean {
  if (!embedding || embedding.length !== 512 || !embedding.every(Number.isFinite)) return false;
  const norm = Math.sqrt(embedding.reduce((sum, value) => sum + value * value, 0));
  return norm >= 0.98 && norm <= 1.02;
}

/**
 * A record is visually usable only when it contains a verified real-pixel
 * analysis generated by the current extractor. Synthetic and legacy vectors
 * may remain in the catalog for metadata lookup, but are never visual evidence.
 */
export function isReliableVisualAnalysis(album: Album): boolean {
  return (
    album.visualAnalysisStatus === 'analyzed' &&
    album.embeddingVersion === VERIFIED_VISUAL_ANALYSIS_VERSION &&
    Boolean(album.perceptualHash) &&
    hasNormalizedDescriptor(album.embedding) &&
    hasValidPalette(album) &&
    hasValidColorProfile(album)
  );
}
