import { Album } from '../lib/types';
import { extractVisualFeaturesFromImage } from '../lib/featureExtractor';

// Synchronous seed album builder.
// Visual features + palette are generated by the seeded RNG in featureExtractor,
// guaranteeing every album gets a UNIQUE set of colours/features from its metadata.
function createSeedAlbum(
  collectionId: number,
  title: string,
  artistName: string,
  genre: string,
  releaseYear: number,
  artworkUrl: string,
  label: string = 'Independent',
): Album {
  const normTitle = title.toLowerCase().trim();
  const normArtist = artistName.toLowerCase().trim();

  // Build the same rich seed that normalizeItunesAlbum uses
  const seed = [
    collectionId,
    title,
    artistName,
    genre,
    releaseYear,
    10, // trackCount placeholder
    artworkUrl,
  ].join('|');

  // extractVisualFeaturesFromImage with null buffer uses the seeded-RNG path
  // We call it synchronously-compatible by pre-computing (the function is async
  // only for the sharp path; the seed path is pure computation).
  // We'll initialise lazily in initSeedAlbums().
  return {
    id: `seed-${collectionId}`,
    itunesCollectionId: collectionId,
    itunesArtistId: 1000 + collectionId,
    title,
    normalizedTitle: normTitle,
    artistName,
    normalizedArtistName: normArtist,
    genre,
    label,
    releaseDate: `${releaseYear}-05-15`,
    releaseYear,
    country: 'PH',
    trackCount: 10,
    explicitness: 'notExplicit',
    price: 9.99,
    currency: 'USD',
    artworkUrl,
    artworkSource: 'seed',
    storeUrl: `https://music.apple.com/ph/album/${collectionId}`,
    dominantPalette: [], // will be filled by initSeedAlbums
    visualFeatures: {} as any,
    perceptualHash: `phash-${collectionId}`,
    embedding: [],
    embeddingModel: 'seed-fallback',
    embeddingVersion: 'fallback-v1',
    _seed: seed, // internal, used by init
  } as any;
}

// Raw seed definitions — palette + features will be auto-generated
const RAW_SEEDS = [
  createSeedAlbum(1440854851, 'Abbey Road', 'The Beatles', 'Rock', 1969,
    'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/a1/59/a4/a159a4be-e28e-5d18-971c-3b3fb31e67e3/00602577914294.rgb.jpg/600x600bb.jpg',
    'Apple Records'),

  createSeedAlbum(1440882340, 'Kind of Blue', 'Miles Davis', 'Jazz', 1959,
    'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/80/96/6b/80966b59-19c9-d2b1-6a2d-20907d0f9a2e/074646493526.jpg/600x600bb.jpg',
    'Columbia Records'),

  createSeedAlbum(1440878589, 'Blue', 'Joni Mitchell', 'Singer/Songwriter', 1971,
    'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/4b/32/38/4b32386e-9844-3fb6-5e5d-4f15a31a9805/603497849208.jpg/600x600bb.jpg',
    'Reprise Records'),

  createSeedAlbum(1440841363, 'Amnesiac', 'Radiohead', 'Alternative', 2001,
    'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/4d/9b/38/4d9b3899-73e4-d50d-d419-74d71597fbb2/634904078320.jpg/600x600bb.jpg',
    'XL Recordings'),

  createSeedAlbum(1440844781, 'Kid A', 'Radiohead', 'Alternative', 2000,
    'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/21/9f/c7/219fc79b-2b47-d5d1-419b-648b788a8d11/634904078023.jpg/600x600bb.jpg',
    'XL Recordings'),

  createSeedAlbum(1440889240, 'Elephant', 'The White Stripes', 'Alternative', 2003,
    'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/71/3b/b7/713bb7f5-937b-402a-c752-df21f7535b71/886443834160.jpg/600x600bb.jpg',
    'Third Man Records'),

  createSeedAlbum(1440845340, 'The Dark Side of the Moon', 'Pink Floyd', 'Rock', 1973,
    'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/da/67/6f/da676f6b-7fa9-0fef-0708-9df2c2199eb6/0094636820120.jpg/600x600bb.jpg',
    'Harvest Records'),

  createSeedAlbum(1440879999, 'Disintegration', 'The Cure', 'Alternative', 1989,
    'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/0d/18/38/0d1838e5-3f3c-8438-e6b8-61cf1c11e61b/603497848881.jpg/600x600bb.jpg',
    'Fiction Records'),

  createSeedAlbum(1440872200, 'Blonde', 'Frank Ocean', 'R&B/Soul', 2016,
    'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/d3/67/78/d36778f8-b34e-4f01-bd31-9257d0793617/886446198641.jpg/600x600bb.jpg',
    'Boys Don\'t Cry'),

  createSeedAlbum(1440822111, 'Channel Orange', 'Frank Ocean', 'R&B/Soul', 2012,
    'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/20/4a/01/204a0149-a297-c81b-8f3e-5a02e6d63428/12UMGIM22384.rgb.jpg/600x600bb.jpg',
    'Def Jam'),

  createSeedAlbum(1440866500, 'In the Aeroplane Over the Sea', 'Neutral Milk Hotel', 'Alternative', 1998,
    'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/6c/aa/89/6caa8901-d851-d418-c511-b0db0d0eb3e1/036172954728.jpg/600x600bb.jpg',
    'Merge Records'),

  createSeedAlbum(1440833100, 'Demon Days', 'Gorillaz', 'Alternative', 2005,
    'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/a7/67/6f/a7676f6b-7fa9-0fef-0708-9df2c2199eb6/0094636820120.jpg/600x600bb.jpg',
    'Parlophone'),

  createSeedAlbum(1440851200, 'Igor', 'Tyler, The Creator', 'Hip-Hop/Rap', 2019,
    'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/44/14/ef/4414ef90-8b0a-42eb-bb84-5a213e843c16/886447738228.jpg/600x600bb.jpg',
    'Columbia Records'),

  createSeedAlbum(1440811900, 'Currents', 'Tame Impala', 'Alternative', 2015,
    'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/45/7b/09/457b0934-8c87-8d07-ee24-9b2f56730bb5/15UMGIM27150.jpg/600x600bb.jpg',
    'Modular Recordings'),

  createSeedAlbum(1440825400, 'Unknown Pleasures', 'Joy Division', 'Alternative', 1979,
    'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/91/9f/8e/919f8e43-d95a-c567-c2cf-3d7503901b0f/825646231264.jpg/600x600bb.jpg',
    'Factory Records'),

  createSeedAlbum(1440899000, 'Yeezus', 'Kanye West', 'Hip-Hop/Rap', 2013,
    'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/6a/d0/0d/6ad00df8-8090-482a-464a-385a864d4b14/13UMGIM22384.rgb.jpg/600x600bb.jpg',
    'Def Jam'),

  createSeedAlbum(1440845111, 'Sgt. Pepper\'s Lonely Hearts Club Band', 'The Beatles', 'Rock', 1967,
    'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/0d/18/38/0d1838e5-3f3c-8438-e6b8-61cf1c11e61b/00602557455328.rgb.jpg/600x600bb.jpg',
    'Apple Records'),

  createSeedAlbum(1440877222, 'Melodrama', 'Lorde', 'Pop', 2017,
    'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/37/10/7a/37107a67-5a1e-874c-bd73-0498dbf5b111/17UMGIM08248.rgb.jpg/600x600bb.jpg',
    'Lava / Republic'),
];

// ─────────────────────────────────────────────────────────────
// Initialise all seed albums with unique features + embeddings
// ─────────────────────────────────────────────────────────────
let _initialised = false;
export const SEED_ALBUMS: Album[] = RAW_SEEDS;

export async function initSeedAlbums(): Promise<void> {
  if (_initialised) return;
  _initialised = true;

  for (const album of SEED_ALBUMS) {
    const seed = (album as any)._seed || `${album.itunesCollectionId}|${album.title}|${album.artistName}`;
    const { palette, features, embedding } = await extractVisualFeaturesFromImage(null, seed);
    album.dominantPalette = palette;
    album.visualFeatures = features;
    album.embedding = embedding;
    delete (album as any)._seed;
  }
}

// Eagerly initialise on module load
initSeedAlbums();
