import { Album } from '../lib/types';
import { extractVisualFeaturesFromImage } from '../lib/featureExtractor';

// Synchronous seed album builder.
// Visual features + palette are generated by the seeded RNG in featureExtractor,
// guaranteeing every album gets a UNIQUE set of colours/features from its metadata.
function createSeedAlbum(
  collectionId: number,
  title: string,
  artistName: string,
  genre: string,
  releaseYear: number,
  artworkUrl: string,
  label: string = 'Independent',
): Album {
  const normTitle = title.toLowerCase().trim();
  const normArtist = artistName.toLowerCase().trim();

  // Build the same rich seed that normalizeItunesAlbum uses
  const seed = [
    collectionId,
    title,
    artistName,
    genre,
    releaseYear,
    10, // trackCount placeholder
    artworkUrl,
  ].join('|');

  // extractVisualFeaturesFromImage with null buffer uses the seeded-RNG path
  // We call it synchronously-compatible by pre-computing (the function is async
  // only for the sharp path; the seed path is pure computation).
  // We'll initialise lazily in initSeedAlbums().
  return {
    id: `seed-${collectionId}`,
    itunesCollectionId: collectionId,
    itunesArtistId: 1000 + collectionId,
    title,
    normalizedTitle: normTitle,
    artistName,
    normalizedArtistName: normArtist,
    genre,
    label,
    releaseDate: `${releaseYear}-05-15`,
    releaseYear,
    country: 'PH',
    trackCount: 10,
    explicitness: 'notExplicit',
    price: 9.99,
    currency: 'USD',
    artworkUrl,
    artworkSource: 'seed',
    storeUrl: `https://music.apple.com/ph/album/${collectionId}`,
    dominantPalette: [], // will be filled by initSeedAlbums
    visualFeatures: {} as any,
    perceptualHash: `phash-${collectionId}`,
    embedding: [],
    embeddingModel: 'seed-fallback',
    embeddingVersion: 'fallback-v1',
    visualAnalysisStatus: 'analyzed',
    _seed: seed, // internal, used by init
  } as any;
}

// Raw seed definitions — palette + features will be auto-generated
const RAW_SEEDS = [
  createSeedAlbum(1474815798, 'Abbey Road', 'The Beatles', 'Rock', 1969,
    'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/48/53/43/485343e3-dd6a-0034-faec-f4b6403f8108/13UMGIM63890.rgb.jpg/600x600bb.jpg',
    'Apple Records'),

  createSeedAlbum(268443092, 'Kind of Blue', 'Miles Davis', 'Jazz', 1959,
    'https://is1-ssl.mzstatic.com/image/thumb/Music/7f/9f/d6/mzi.vtnaewef.jpg/600x600bb.jpg',
    'Columbia Records'),

  createSeedAlbum(1492263092, 'Blue', 'Joni Mitchell', 'Singer/Songwriter', 1971,
    'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/00/a2/43/00a24363-cf69-bfd2-a26a-a042d57ab141/075992719926.jpg/600x600bb.jpg',
    'Reprise Records'),

  createSeedAlbum(1097864180, 'Amnesiac', 'Radiohead', 'Alternative', 2001,
    'https://is1-ssl.mzstatic.com/image/thumb/Music122/v4/43/d8/ec/43d8ec17-0e96-dba9-21d9-4cdf9d98f2bf/634904078362.png/600x600bb.jpg',
    'XL Recordings'),

  createSeedAlbum(1097862870, 'Kid A', 'Radiohead', 'Alternative', 2000,
    'https://is1-ssl.mzstatic.com/image/thumb/Music122/v4/bd/8e/13/bd8e1358-b367-a689-cb84-cebd0b067dc4/634904078263.png/600x600bb.jpg',
    'XL Recordings'),

  createSeedAlbum(1675379752, 'Elephant', 'The White Stripes', 'Alternative', 2003,
    'https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/48/b5/b9/48b5b90e-ba1e-08ff-1217-9e479afdad5d/196589901750.jpg/600x600bb.jpg',
    'Third Man Records'),

  createSeedAlbum(1065975633, 'The Dark Side of the Moon', 'Pink Floyd', 'Rock', 1973,
    'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/3e/17/ec/3e17ec6d-f980-c64f-19e0-a6fd8bbf0c10/886445635850.jpg/600x600bb.jpg',
    'Harvest Records'),

  createSeedAlbum(372100016, 'Disintegration', 'The Cure', 'Alternative', 1989,
    'https://is1-ssl.mzstatic.com/image/thumb/Music/93/3c/2c/mzi.ujtdsknz.jpg/600x600bb.jpg',
    'Fiction Records'),

  createSeedAlbum(1445278500, 'Blonde', 'Frank Ocean', 'R&B/Soul', 2016,
    'https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/8d/76/23/8d76234b-5101-fa9b-58b3-5e17645d5b05/00602527744209.rgb.jpg/600x600bb.jpg',
    'Boys Don\'t Cry'),

  createSeedAlbum(1506122308, 'Channel Orange', 'Frank Ocean', 'R&B/Soul', 2012,
    'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/d8/9a/fa/d89afa00-abe3-c5c2-0cd3-935eebd32129/843357195384_01_img001.jpg/600x600bb.jpg',
    'Def Jam'),

  createSeedAlbum(1839077554, 'In the Aeroplane Over the Sea', 'Neutral Milk Hotel', 'Alternative', 1998,
    'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/12/e3/5c/12e35c39-de5c-b501-3ef0-00f19fb3d513/56627.jpg/600x600bb.jpg',
    'Merge Records'),

  createSeedAlbum(850571319, 'Demon Days', 'Gorillaz', 'Alternative', 2005,
    'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/1c/0f/81/1c0f818a-e458-dd84-6f1b-ccbdf5fe14d6/825646291045.jpg/600x600bb.jpg',
    'Parlophone'),

  createSeedAlbum(1444322705, 'Igor', 'Tyler, The Creator', 'Hip-Hop/Rap', 2019,
    'https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/22/fd/10/22fd10a3-881d-2560-64e7-a9df650b9e47/17UM1IM42651.rgb.jpg/600x600bb.jpg',
    'Columbia Records'),

  createSeedAlbum(1440875696, 'Currents', 'Tame Impala', 'Alternative', 2015,
    'https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/64/48/5c/64485cc9-968c-68cc-764e-9a7c71733def/00602567155454.rgb.jpg/600x600bb.jpg',
    'Modular Recordings'),

  createSeedAlbum(1476702180, 'Unknown Pleasures', 'Joy Division', 'Alternative', 1979,
    'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/13/90/c0/1390c072-4249-3739-7b3d-fd73ee4a5698/825646562831.jpg/600x600bb.jpg',
    'Factory Records'),

  createSeedAlbum(1587795158, 'Yeezus', 'Kanye West', 'Hip-Hop/Rap', 2013,
    'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/62/13/7b/62137b3f-7722-59f5-2ee1-b5aff9426869/21UMGIM64738.rgb.jpg/600x600bb.jpg',
    'Def Jam'),

  createSeedAlbum(1441164604, 'Sgt. Pepper\'s Lonely Hearts Club Band', 'The Beatles', 'Rock', 1967,
    'https://is1-ssl.mzstatic.com/image/thumb/Music114/v4/6f/79/8d/6f798d84-7475-8525-fc91-f7b51b2b5a9b/00602567725428.rgb.jpg/600x600bb.jpg',
    'Apple Records'),

  createSeedAlbum(1428764777, 'Melodrama', 'Lorde', 'Pop', 2017,
    'https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/58/11/b1/5811b172-e180-25a6-69e6-4385fbbfb5dc/17UM1IM02207.rgb.jpg/600x600bb.jpg',
    'Lava / Republic'),
];

// ─────────────────────────────────────────────────────────────
// Initialise all seed albums with unique features + embeddings
// ─────────────────────────────────────────────────────────────
let initialisationPromise: Promise<void> | null = null;
export const SEED_ALBUMS: Album[] = RAW_SEEDS;

export function initSeedAlbums(): Promise<void> {
  if (!initialisationPromise) {
    initialisationPromise = (async () => {
      for (const album of SEED_ALBUMS) {
        const seed = (album as any)._seed || `${album.itunesCollectionId}|${album.title}|${album.artistName}`;
        const { palette, features, embedding } = await extractVisualFeaturesFromImage(null, seed);
        album.dominantPalette = palette;
        album.visualFeatures = features;
        album.embedding = embedding;
        album.visualAnalysisStatus = 'analyzed';
        delete (album as any)._seed;
      }
    })();
  }
  return initialisationPromise;
}
